### PR TITLE
UPSTREAM: docker/distribution: 3403: add application-credential auth support for swift storage driver 

### PR DESCRIPTION
**Pull request by bverschueren**
This add the ability to authenticate the Swift storage driver using keystone application credentials (by id/name).

### CODE REVIEW

**Comment by bverschueren** [comment]
@dmage @adambkaplan any thoughts ?

**Comment by dmage** [comment]
@bverschueren do have a Jira issue for that?

**Comment by bverschueren** [comment]
There is https://issues.redhat.com/browse/OSASINFRA-1934 which is related.

**Comment by dmage** [comment]
@bverschueren please bump docker-distribution in image-registry

**Pull request merged**
