### PR TITLE
UPSTREAM: distribution/distribution: 2815 Add code to handle pagination of parts. Fixes max layer size of 10GB bug

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by dmage** [comment]
@flavianmissi is it 2815 or 3840?

**Comment by flavianmissi** [comment]
2815 is already merged (onto distribution's main branch), so I thought it made more sense to refer to 3840 (the backport to the 2.8 release branch) instead. Additionally, both PR IDs are mentioned in the commit, 3840 is in the commit title, while 2815 is in the commit body.

I recognize that we don't often do backports like this though, so I guess this PR is a little odd...

WDYT?

**Comment by dmage** [comment]
Nobody reads the commit body when they rebase changes - we have all necessary information in the first line. In your case it should be

```
UPSTREAM: distribution/distribution: 2815: Add code to handle pagination of parts. Fixes max layer size of 10GB bug
```

We do it this way because rebasing is already an error-prone task and we want to make it a no-brainer task.

That's what we have so far:

```
* 8f8f87be UPSTREAM: distribution/distribution: 3647: Allow google oauth client to consume creds for workload identity
* c7c6b8ab UPSTREAM: distribution/distribution: 3647: update golang.org/x/oauth2 to support gcp workload identity
* c4bec89e UPSTREAM: docker/distribution: 3403: add application-credential support for swift driver
* e17c9709 UPSTREAM: docker/distribution: 3057: allow for optional S3 debugging
* db33aa74 UPSTREAM: docker/distribution: 3296: allow pointing to an AWS config file as a parameter for the s3 driver
* 76ff21cc UPSTREAM: docker/distribution: 3248: Ignore self reference object on empty prefix
* 0a438da6 UPSTREAM: docker/distribution: 3131: Remove VirtualHostedStyle from driver struct
* 76ad0646 UPSTREAM: docker/distribution: 3131: Add VirtualHostedStyle to struct
* 7d25ebd9 UPSTREAM: docker/distribution: 3131: Add S3 virtual hosted style paths for custom region endpoints
* b0b174c5 UPSTREAM: docker/distribution: 3127: Fix err shadowing in gcs driver
* ac0de34c UPSTREAM: docker/distribution: 3068: Add dualstack option to S3 storage driver
* dc14d118 UPSTREAM: docker/distribution: <carry>: use application logger for requests
* b58d09a8 UPSTREAM: docker/distribution: <carry>: Do not hide reader error
* 99677704 UPSTREAM: docker/distribution: <carry>: Log failed HEAD requests as a info
* ebcaafd4 UPSTREAM: docker/distribution: <carry>: Prevent wrapping of errcode.Error
* 61bc5d2b UPSTREAM: docker/distribution: 2446: Fix the pointer initialization
* 1bb07077 UPSTREAM: docker/distribution: 2580: Allow to use custom cache provider
* 74735e54 UPSTREAM: docker/distribution: <carry>: custom routes/auth
```

We have two problematic PRs:
3131 - the author closed it, probably we should open a new one.
3248 - we should re-backport it on next rebase.

3840 is closed without being merged. If I were rebasing this change, this would confuse me and distract from rebasing.

**Comment by flavianmissi** [comment]
> 3840 is closed without being merged. If I were rebasing this change, this would confuse me and distract from rebasing.

dammit, I did that by accident 🙄 

I'll point to the original PR instead to avoid confusion.

**Comment by dmage** [comment]
/lgtm
/hold
feel free to remove the hold when you are ready

**Pull request merged**
