### PR TITLE
UPSTREAM: docker/distribution: 2446: Fix the pointer initialization

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@legionus @deads2k ptal

**Comment by bparees** [comment]
@deads2k does this align w/ your expectations?

i'm having some second thoughts about the branch name...  would it make more sense to name the branch for the origin release it's aligned around?  (e.g. image-registry-release-3.9 in this case).  The downside to that is having to create new branches every release even if we haven't moved to a new docker distribution version.

**Comment by deads2k** [comment]
> @deads2k does this align w/ your expectations?

It does.



> i'm having some second thoughts about the branch name... would it make more sense to name the branch for the origin release it's aligned around? (e.g. image-registry-release-3.9 in this case). The downside to that is having to create new branches every release even if we haven't moved to a new docker distribution version.

Exploring the idea: let's say there was an upstream bug fix we were picking.  We would know the upstream PR number and the branch it made it into upstream.  If we follow the upstream numbers, we can work in both directions: from the image-registry -> glide.yaml -> upstream branch and upstream branch -> openshift/fork branch -> image-registry.  Using branch names based on upstream releases will let us fix the problem once and vendor it in.  Using branch names based on origin releases will mean that we have to manually check each version and branch, figure out where the common commit is, trace that to an upstream branch to determine if we're affected and we'd have to do it for every origin release.

I think the maintenance is easier if we have our fork's branches track upstream release names.

**Comment by bparees** [comment]
I guess my converse concern is:

Suppose in the 3.9 timeframe we introduce a carry in 2.6.2
Then in 3.10, also based on 2.6.2, we want to introduce a second carry
Then suppose for some other reason we need to go back and patch 2.6.2 for an issue found in 3.9.  We are forced to pick up the change we made for 3.10.  Maybe that's desirable, but in general i'd prefer more control over the changes.

I agree the maintenance is harder, but w/o a dependency branch per release, we can't guarantee we can patch what we shipped cleanly.

**Comment by bparees** [comment]
(I still want to have the branch naming discussion, but it doesn't need to hold up this PR)

**Comment by bparees** [comment]
(this PR updated the wrong line, i've rewritten the history for the branch to fix it and keep things clean)

**Comment by bparees** [comment]
commit is here: https://github.com/openshift/docker-distribution/commit/588ea2c42a2ebb5c06cd01dbeabfe60e4a7075df

**Pull request merged**
